version: "3"

services:
  geo:
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - mylos
  redis:
    image: redis
    networks:
      - mylos
networks:
  mylos:
    external: true